### ISSUE TITLE
MQTT is not available in athom device b32

### ISSUE THREAD

**Issue by zandegran** [MoonModules/WLED#159]
I have been using MQTT and it's not available anymore :)

**Comment by softhack007** [comment]
hi,

we ha to disable some features because program space in flash was used at almost 100%.
> Flash: [==========]  96.5% (used 1518509 bytes from 1572864 bytes)

I've just changed the buildenv for athom a bit - removing ArtiFX, rotary encoder and dallas temperature support allows to re-enable MQTT.

you can find a firmware bin in the github build job
https://github.com/MoonModules/WLED/actions/runs/10549264058
scroll down to "Artifacts".

**Comment by softhack007** [comment]
closing as there was no more feedback from the problem reporter.

Important: only the athom firmware binary was modified. All other firmware images are the same as before.

**Comment by zandegran** [comment]
Thank you @softhack007 Working as expected

**Comment by zandegran** [comment]
Does this solve mqtt for future updates though?

**Comment by softhack007** [comment]
> Does this solve mqtt for future updates though?

Yes, as long as we don't run out of flash space again.

Because I still prefer "no MQTT" over "no firmware".
