### ISSUE TITLE
No Analog Input Option in WLEDMM_0.14.0-b15.21_esp32S3_8MB_M.bin

### ISSUE THREAD

**Issue by tobeehh** [MoonModules/WLED#56]
### What happened?

I find no analog input option in [WLEDMM_0.14.0-b15.21_esp32S3_8MB_M.bin](https://github.com/MoonModules/WLED/releases/download/v0.14.0.b15/WLEDMM_0.14.0-b15.21_esp32S3_8MB_M.bin)

I would like to use max9814 mic

### To Reproduce Bug

Install
[WLEDMM_0.14.0-b15.21_esp32S3_8MB_M.bin](https://github.com/MoonModules/WLED/releases/download/v0.14.0.b15/WLEDMM_0.14.0-b15.21_esp32S3_8MB_M.bin)
Check sound Reactive section

### Expected Behavior

To be able to set analog input

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

WLEDMM_0.14.0-b15.21_esp32S3_8MB_M.bin

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
S3 does not support analog microphone  .Go digital

**Comment by softhack007** [comment]
Unfortunately ESP32-S3 (and -s2/c3) do not support analog microphone and analog line-in. 
So its expected behaviour that firmware for these boards is not showing any analog input options.

Technicially speaking, espressif have removed ADC-analog features from the I2S driver we use, so nothing that we can do about that, sorry.
